.github/ISSUE_TEMPLATE/config.yml

- Disable blank issues.
- Disable blank issues as there's already a miscellaneous issue template provided.
None.

fix: disable blank issues

---

pages/Cheatsheet.md

fix: the wrong `<br>` tag in `pages/Cheatsheet.md`

---

pages/Bootcamp.md
pages/Cheatsheet.md

removed br on webpage

---

pages/Cheatsheet.md

Fix: center align header

---

pages/How-to/guide/starting-discussion.md

fixes #21 
- Add process/guide - "How to start a github discussion"
- Hope this works

Add process/guide - "How to start a github discussion"

---

pages/How-to/guide/adding-issue-template.md
pages/How-to/guide/adding-pr-template.md
pages/How-to/guide/adding-sponsor.md
pages/How-to/guide/assigning-issue.md
pages/How-to/guide/cloning-repo.md
pages/How-to/guide/creating-pr.md
pages/How-to/guide/linking-issue-with-pr.md
pages/How-to/guide/rasing-issue.md
pages/How-to/guide/reviewing-pr.md

fix: Chnage the tag from `<div>` to `<p>`

---

README.md

Closes #46 
Fixed two typos in Learning Resources Section.
1. In the Description.
2. In the Page (Link- clickable)

Fix: Typos in README.md

---

pages/How-to/guide/cloning-repo.md

Closes #15 
Process/guide added for cloning a repo

docs: Add "How to clone a repo" in `How to` guide

---

README.md
pages/Faq.md

- Added a FAQ page
- Added some questions in that FAQ page

feat: Add `Faq,md` and some answer in that.

---

_layouts/navbar.md
_layouts/sidebar.md
index.html

feat: Added navbar and sidebar on the website

---

README.md

Removed the hyperlink from `Pages`

---

pages/Beginners.md

Fix: Typo in `Beginners.md`

---

.github/workflows/greetings.yml

Added action that will greet people when a fresh and issue and PR will open

ci: added greeting workflow

---

.github/workflows/releases.yml

- Added auto-release (conventional) workflow which works on sematic versioning

ci: Added conventional release workflow

---

pages/How-to/guide/star-repo.md

Closes #66
👨‍💻 Changes proposed
Added the complete procedure for starring a repository along with the necessary screenshots
✔️ Check List (Check all the applicable boxes)

docs: Add guide - "how to star a repo"

---

pages/How-to/guide/adding-pr-template.md

Closes #11 
Added the complete procedure to be followed in order to make a PR Template.
Added a demo video with all the related screen shots 
cc - @Pradumnasaraf

docs: Add process - "how to create a PR Template"

---

pages/How-to/guide/linking-issue-with-pr.md

fixes #17 Added the process of, **"How to Link and Issue no with a PR"**

docs: Add Process "How to link an Issue to a PR"

---

pages/How-to/guide/fork-repo.md

Closes #67
Added a step-to-step guide on How to fork a repository.

docs: Add Process "How to fork a repo"

---

pages/How-to/guide/reviewing-pr.md

Closes #20 
I have added the complete process to review a PR.
Hey, @Pradumnasaraf I have made this new PR for issue #20.

docs: Add process "How to review a PR"

---

pages/Beginners.md

#77
- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.
Tried to fix the spelling error !

docs: Spelling mistake correction

---

pages/How-to/README.md

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

fix: Updated typo in `How to`

---

pages/How-to/guide/adding-sponsor.md

Closes #13 
Added a step-by-step guide to add the sponsor button.

docs: Added process "Adding a sponsor button"

---

pages/How-to/guide/raise-issue-template.md

Below mentioned is the main article that I have updated today by editing typos, streamlining content - 
https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/raise-issue-template.md 
Had previously raised an issue for the same at - 
https://github.com/Pradumnasaraf/open-source-with-pradumna/issues/84 
Hope you find this useful Pradumna.

Updated 'How to create an issue'?

---

pages/How-to/guide/creating-pr.md
pages/How-to/guide/raise-issue-template.md

Anieshak patch 1

---

pages/Regular.md

closes #88 
Documentation links in Pages/Regular.md
Corrected the links that are wrongly documented in first 2 Twitter posts.

docs: fix the wrong Twitter post link

---

pages/How-to/guide/social-preview.md

Closes #93
Added a step-by-step guide on how to add a social preview to a repository

docs: Add process "How to add social preview to a repo"

---

README.md
_layouts/navbar.md
_layouts/sidebar.md

- Change domain form `opensource.pradumnasaraf.co` to `oswp.study`

chore: Domain change

---

pages/How-to/guide/archive-repo.md

docs: Add process "How to archive a repo" 

---

pages/How-to/guide/delete-the-repo.md

docs: Add process "How to create delete a repo"

---

pages/How-to/guide/create-releases.md

Added the `create-release.md` file which describes on how to create releases on your repository

docs: Add process "How to create a Releases - Manually"

---

pages/Beginners.md

Added alt attribute to images for better accessibility.

fix: Update alt text in `Beginners.md`

---

pages/Regular.md

`Closes #101`
Updated typos in Regular.md doc
Changed  conetent to content in Regular.md doc

Typos corrected in Regular.md doc

---

pages/How-to/guide/assigning-issue.md

Closes #138
-Added images that better convey what and where the reader must click
-Added a step for labels because labels are helpful when creating an issue
-Made more descriptive and detailed steps to better guide the reader

Adding more information to assigning-issues.md

---

pages/How-to/guide/adding-pr-template.md

docs: Add alt attribute to images in 'adding-pr-template.md'

---

pages/Resources.md

- Closes  #122 
- added eddie jaoude's github course in learning resources.

docs: Added Eddie Jaoude's GitHub profile course in learning resources #122

---

pages/How-to/guide/adding-sponsor.md

Closes #132 
Updated all the alt texts of all images

Updated alt texts of images

---

pages/How-to/guide/creating-pr.md

Resolved and Added Alt Description to  Issue #130 creating-pr.md file.

Added Alt Description

---

pages/How-to/guide/github-pages.md

Closes #94 
This pull request added content to the <a href="https://oswp.study/#/pages/How-to/guide/github-pages">Use github pages</a> section in "How to" section of the OSWP site.

docs: Added process - How to use GitHub Pages

---

pages/Faq.md

Fixing this issue #150 by correcting the punctuation.

Correct punctuation in Faq.md docs

---

.github/FUNDING.yml

Solve issue related funding

---

pages/How-to/guide/creating-pr.md

Closes #131 
I centered the images in creating-pr.md. Kindly review the changes. Thank you!

Images in creating-pr doc were centered

---

pages/How-to/guide/linking-issue-with-pr.md

closes #134 
Updated alt text of images
- [✔] My code follows the code style of this project.
- [✔] This PR does not contain plagiarized content.
- [✔] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/173"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Updated alt text of images

---

pages/How-to/guide/rasing-issue.md

Closes: #129
1. Center the Images

Fix: Center the images

---

pages/How-to/guide/reviewing-pr.md

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/171"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

center the images in the review_pr.md file

---

pages/How-to/README.md

- Fixed a few typos in the markdown
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/191"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix #190: Typo in pages/How-to/README.md

---

README.md

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/195"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fixed typo and grammar error in ReadMe

---

pages/How-to/guide/create-project-board.md

issue  #206 
1. Typo in the sub-heading
2. Added a GIF in place of a video which is not rendered, and added a subheading.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/207"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

BUGS FIXED: Added GIF and Typos cleared

---

pages/How-to/guide/create-tags.md

Added instructions in create-tags.md
- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/186"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added instructions

---

pages/How-to/README.md
pages/How-to/guide/create-branch.md

Created a new section for "How to create a new branch" and also "How you can change from an existing branch"
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/221"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

How to create a branch

---

pages/How-to/guide/star-repo.md

Added alt attribute to <img> tag in star-repo.md 
closes #225 
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/226"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update start repo.md

---

.github/workflows/tweet.yml

Changes will make a Twitter on the handle https://twitter.com/OSWP__

ci: Add auto tweet workflow

---

pages/How-to/guide/create-template-repo.md

Closes #227 
I have created a README file explaining steps to create a repository template
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/231"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add : create-template-repo.md

---

_layouts/navbar.md
index.html
pages/Faq.md
pages/Resources.md

- Fix the ` _layouts/navbar.md`
- Improve docs in `pages/Faq.md`
- Added resources in `pages/Resources.md`

docs: improve docs

---

.dockerignore

chore: improve .dockerignore

---

README.md

Added a Bold Tag with the GitHub Sponsors link inside the `README.md` file and tested it successfully, now It will render properly inside the main site as well as in the markdown format too.
None
None

fix: sponsor message in the README

---

pages/How-to/README.md
pages/How-to/guide/use-github-gists.md

Closes #270 
Added Graphic for 'Use Gist' as proposed in #270 by @Pradumnasaraf 
Also, added required docs at 'guide' on the same
Raising this PR after getting the go-ahead from Pradumna. Hey, @Pradumnasaraf please review the PR, and add `hacktoberfest-accepted` label to it. Thank you.

Add docs for 'GitHub Gists'

---

.github/workflows/greetings.yml
.github/workflows/publish-dockerhub.yml
.github/workflows/publish-ghcr.yml
.github/workflows/releases.yml

Updated DockerHub and GHCR push actions to use the new Docker `buildx` action to build and push multi-arch images.

fix: add support for multi-arch for Docker images
